import {store} from "../utils/internal-store-utils" ;
interface Permissions {
  [key: string]: boolean
}
const permissions: Permissions = {
  'FeatureManagement.ManageHostFeatures': true,
  'AbpIdentity.Roles': true,
  'AbpIdentity.Roles.Create': true,
  'AbpIdentity.Roles.Update': true,
  'AbpIdentity.Roles.Delete': true,
  'AbpIdentity.Roles.ManagePermissions': true,
  'AbpIdentity.Users': true,
  'AbpIdentity.Users.Create': true,
  'AbpIdentity.Users.Update': true,
  'AbpIdentity.Users.Delete': true,
  'AbpIdentity.Users.ManagePermissions': true,
  'AbpIdentity.Users.Update.ManageRoles': true,
  'AbpIdentity.Users.Update.ManageOU': true,
  'AbpIdentity.Users.Impersonation': true,
  'AbpIdentity.Users.Import': true,
  'AbpIdentity.OrganizationUnits': true,
  'AbpIdentity.OrganizationUnits.ManageOU': true,
  'AbpIdentity.OrganizationUnits.ManageRoles': true,
  'AbpIdentity.OrganizationUnits.ManageMembers': true,
  'AbpIdentity.ClaimTypes': true,
  'AbpIdentity.ClaimTypes.Create': true,
  'AbpIdentity.ClaimTypes.Update': true,
  'AbpIdentity.ClaimTypes.Delete': true,
  'AbpIdentity.SettingManagement': true,
  'AbpIdentity.SecurityLogs': true,
  'SettingManagement.Emailing': true,
  'SettingManagement.Emailing.Test': true,
  'Saas.Tenants': true,
  'Saas.Tenants.Create': true,
  'Saas.Tenants.Update': true,
  'Saas.Tenants.Delete': true,
  'Saas.Tenants.ManageFeatures': true,
  'Saas.Tenants.ManageConnectionStrings': true,
  'Saas.Tenants.SetPassword': true,
  'Saas.Tenants.Impersonation': true,
  'Saas.Editions': true,
  'Saas.Editions.Create': true,
  'Saas.Editions.Update': true,
  'Saas.Editions.Delete': true,
  'Saas.Editions.ManageFeatures': true,
  'AuditLogging.AuditLogs': true,
  'OpenIddictPro.Application': true,
  'OpenIddictPro.Application.Update': true,
  'OpenIddictPro.Application.Delete': true,
  'OpenIddictPro.Application.Create': true,
  'OpenIddictPro.Application.ManagePermissions': true,
  'AuditLogging.ViewChangeHistory:Volo.Abp.OpenIddict.Pro.Applications.Application':
    true,
  'OpenIddictPro.Scope': true,
  'OpenIddictPro.Scope.Update': true,
  'OpenIddictPro.Scope.Delete': true,
  'OpenIddictPro.Scope.Create': true,
  'AuditLogging.ViewChangeHistory:Volo.Abp.OpenIddict.Pro.Scopes.Scope': true,
  'AbpAccount.SettingManagement': true,
  'LanguageManagement.LanguageTexts': true,
  'LanguageManagement.LanguageTexts.Edit': true,
  'LanguageManagement.Languages': true,
  'LanguageManagement.Languages.Create': true,
  'LanguageManagement.Languages.Edit': true,
  'LanguageManagement.Languages.ChangeDefault': true,
  'LanguageManagement.Languages.Delete': true,
  'TextTemplateManagement.TextTemplates': true,
  'TextTemplateManagement.TextTemplates.EditContents': true,
  'FileManagement.DirectoryDescriptor': true,
  'FileManagement.DirectoryDescriptor.Create': true,
  'FileManagement.DirectoryDescriptor.Update': true,
  'FileManagement.DirectoryDescriptor.Delete': true,
  'FileManagement.FileDescriptor': true,
  'FileManagement.FileDescriptor.Create': true,
  'FileManagement.FileDescriptor.Update': true,
  'FileManagement.FileDescriptor.Delete': true,
  'Forms.Form': true,
  'Forms.Form.Delete': true,
  'Forms.Response': true,
  'Forms.Response.Delete': true,
  'Blogging.Blog': true,
  'Blogging.Blog.Management': true,
  'Blogging.Blog.Update': true,
  'Blogging.Blog.Delete': true,
  'Blogging.Blog.Create': true,
  'Blogging.Blog.ClearCache': true,
  'Blogging.Post': true,
  'Blogging.Post.Update': true,
  'Blogging.Post.Delete': true,
  'Blogging.Post.Create': true,
  'Blogging.Tag': true,
  'Blogging.Tag.Update': true,
  'Blogging.Tag.Delete': true,
  'Blogging.Tag.Create': true,
  'Blogging.Comment': true,
  'Blogging.Comment.Update': true,
  'Blogging.Comment.Delete': true,
  'Blogging.Comment.Create': true,
  'Payment.Plans': true,
  'Payment.Plans.Create': true,
  'Payment.Plans.Update': true,
  'Payment.Plans.Delete': true,
  'Payment.Plans.GatewayPlans': true,
  'Payment.Plans.GatewayPlans.Create': true,
  'Payment.Plans.GatewayPlans.Update': true,
  'Payment.Plans.GatewayPlans.Delete': true,
  'Payment.PaymentRequests': true,
  'CmsKit.Comments': true,
  'CmsKit.Comments.Delete': true,
  'CmsKit.Tags': true,
  'CmsKit.Tags.Create': true,
  'CmsKit.Tags.Update': true,
  'CmsKit.Tags.Delete': true,
  'CmsKit.Pages': true,
  'CmsKit.Pages.Create': true,
  'CmsKit.Pages.Update': true,
  'CmsKit.Pages.Delete': true,
  'CmsKit.Pages.SetAsHomePage': true,
  'CmsKit.Blogs': true,
  'CmsKit.Blogs.Create': true,
  'CmsKit.Blogs.Update': true,
  'CmsKit.Blogs.Delete': true,
  'CmsKit.Blogs.Features': true,
  'CmsKit.BlogPosts': true,
  'CmsKit.BlogPosts.Create': true,
  'CmsKit.BlogPosts.Update': true,
  'CmsKit.BlogPosts.Delete': true,
  'CmsKit.BlogPosts.Publish': true,
  'CmsKit.Menus': true,
  'CmsKit.Menus.Create': true,
  'CmsKit.Menus.Update': true,
  'CmsKit.Menus.Delete': true,
  'CmsKit.GlobalResources': true,
  'CmsKit.Newsletter': true,
  'CmsKit.Poll': true,
  'CmsKit.Poll.Create': true,
  'CmsKit.Poll.Update': true,
  'CmsKit.Poll.Delete': true,
  'CmsKit.SettingManagement': true,
  'CmsKit.UrlShorting': true,
  'CmsKit.UrlShorting.Create': true,
  'CmsKit.UrlShorting.Update': true,
  'CmsKit.UrlShorting.Delete': true,
  'BookStore.Dashboard.Host': true,
  'BookStore.Books': true,
  'BookStore.Books.Create': true,
  'BookStore.Books.Delete': true
}


export const grantedpolicies = (policy: string): any => {
    if(permissions.hasOwnProperty(policy)){
       return true
    } else {
       false
    }
}
export default grantedpolicies
