import { ReactNode } from "react";
import { colors, placements } from "../../libs";

export interface RdsButtonProps {
    submit?: boolean;
    count?: number;
    isFabIcon?: false;
    isRounded?: false;
    id?: string;
    buttonId?: string;
    isLoading?: boolean;
    showLoadingSpinner?: boolean;
    children?: ReactNode;
    isDisabled?: boolean;
    colorVariant?: colors;
    label?: string;
    block?: boolean;
    size?: string;
    roundedButton?: boolean;
    roundedCorner?: boolean;
    icon?: string;
    isOutline?: boolean;
    tooltip?: boolean;
    tooltipPlacement?: placements;
    tooltipTitle?: string;
    type: "button" | "submit";
    onClick?: React.MouseEventHandler<HTMLButtonElement>;
    formName?: string;
    iconHeight?: string;
    iconWidth?: string;
    iconFill?: boolean;
    iconStroke?: boolean;
    class?: string;
    arialabel?: string;
    databsdismiss?: string;
    databstarget?: string;
    databstoggle?: string;
    ariacontrols?: string;
    iconColorVariant?: string;
    style?: any;
    turnSpinnerOff?:any
};
